version: "3.9"
services:
  app:
    image: node:lts-stretch
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - "8080:8080"
    command: "npm start"
    environment:
      - PORT=8080